# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import superlachaise.models.openstreetmap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenStreetMapElement',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('raw_tags', models.TextField(default='{}', validators=[superlachaise.models.openstreetmap.validate_JSON])),
            ],
            options={
                'verbose_name': 'OpenStreetMap element',
                'verbose_name_plural': 'OpenStreetMap elements',
                'ordering': ['id'],
            },
        ),
    ]
