# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonsCategory',
            fields=[
                ('id', models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False)),
                ('default_sort', models.CharField(blank=True, default='', max_length=1024)),
                ('image', models.CharField(blank=True, default='', max_length=1024)),
                ('redirect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.CommonsCategory')),
            ],
            options={
                'verbose_name': 'Commons category',
                'verbose_name_plural': 'Commons categories',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='openstreetmapelement',
            name='id',
            field=models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_openstreetmap_id]),
        ),
        migrations.AlterField(
            model_name='openstreetmapelement',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='wikidataentry',
            name='id',
            field=models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikidata_id]),
        ),
        migrations.AlterField(
            model_name='wikipediapage',
            name='default_sort',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='wikidataentry',
            name='commons_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.CommonsCategory'),
        ),
    ]
