# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0001_openstreetmapelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataEntry',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikidata_id])),
                ('raw_json', models.TextField(default='{}', validators=[superlachaise.models.model_validators.validate_JSON], verbose_name='raw JSON')),
            ],
            options={
                'verbose_name': 'Wikidata entry',
                'verbose_name_plural': 'Wikidata entries',
                'ordering': ['id'],
            },
        ),
    ]
