# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaPage',
            fields=[
                ('id', models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikipedia_id])),
                ('default_sort', models.CharField(blank=True, default='', max_length=255)),
                ('extract', models.TextField(blank=True, default='')),
                ('wikidata_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.WikidataEntry')),
            ],
            options={
                'verbose_name': 'Wikipedia page',
                'verbose_name_plural': 'Wikipedia pages',
                'ordering': ['id'],
            },
        ),
    ]
