# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikimediacommonsCategory',
            fields=[
                ('id', models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False)),
                ('wikitext', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Wikimediacommons category',
                'verbose_name_plural': 'Wikimediacommons categories',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='wikidataentry',
            name='wikimediacommons_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.WikimediacommonsCategory'),
        ),
    ]
