# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0002_auto_20170412_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataCategory',
            fields=[
                ('id', models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikidata_id])),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('raw_labels', models.TextField(default='{}', validators=[superlachaise.models.model_validators.validate_JSON])),
            ],
            options={
                'verbose_name': 'Wikidata category',
                'verbose_name_plural': 'Wikidata categories',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='commonscategory',
            options={'ordering': ['default_sort', 'id'], 'verbose_name': 'Commons category', 'verbose_name_plural': 'Commons categories'},
        ),
        migrations.RemoveField(
            model_name='wikipediapage',
            name='extract',
        ),
        migrations.AlterField(
            model_name='wikidataentry',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='wikidataentry',
            name='wikidata_categories',
            field=models.ManyToManyField(blank=True, to='superlachaise.WikidataCategory'),
        ),
    ]
