# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0002_auto_20170411_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikimediacommonsCategory',
            new_name='CommonsCategory',
        ),
        migrations.AlterModelOptions(
            name='commonscategory',
            options={'ordering': ['id'], 'verbose_name': 'Commons category', 'verbose_name_plural': 'Commons categories'},
        ),
        migrations.RenameField(
            model_name='wikidataentry',
            old_name='wikimediacommons_category',
            new_name='commons_category',
        ),
    ]
