# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0002_wikipediapage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipediapage',
            name='wikidata_entry',
        ),
        migrations.AddField(
            model_name='wikidataentry',
            name='wikipedia_pages',
            field=models.ManyToManyField(blank=True, to='superlachaise.WikipediaPage'),
        ),
    ]
