# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0002_auto_20170412_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonscategory',
            options={'ordering': ['default_sort', 'id'], 'verbose_name': 'Commons category', 'verbose_name_plural': 'Commons categories'},
        ),
        migrations.AlterField(
            model_name='wikidataentry',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
