# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0003_auto_20170413_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipediapage',
            name='extract',
        ),
    ]
