# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0003_auto_20170430_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidatacategory',
            name='id',
            field=models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikidata_category_id]),
        ),
    ]
