# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0003_auto_20170409_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipediapage',
            options={'ordering': ['default_sort', 'id'], 'verbose_name': 'Wikipedia page', 'verbose_name_plural': 'Wikipedia pages'},
        ),
    ]
