# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0004_remove_wikipediapage_extract'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataCategory',
            fields=[
                ('id', models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikidata_id])),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('raw_labels', models.TextField(default='{}', validators=[superlachaise.models.model_validators.validate_JSON])),
            ],
            options={
                'verbose_name': 'Wikidata category',
                'verbose_name_plural': 'Wikidata categories',
                'ordering': ['id'],
            },
        ),
    ]
