# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import superlachaise.models.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0004_auto_20170430_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False, validators=[superlachaise.models.model_validators.validate_wikidata_category_id])),
                ('raw_labels', models.TextField(default='{}', validators=[superlachaise.models.model_validators.validate_JSON])),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='wikidatacategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.Category'),
        ),
    ]
