# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0004_auto_20170430_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediapage',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.WikipediaPage'),
        ),
    ]
