# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0004_auto_20170408_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidataentry',
            name='secondary_entries',
            field=models.ManyToManyField(blank=True, to='superlachaise.WikidataEntry'),
        ),
    ]
