# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0005_v0_5_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonscategory',
            old_name='image',
            new_name='main_image',
        ),
    ]
