# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0005_wikidatacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidataentry',
            name='wikidata_categories',
            field=models.ManyToManyField(blank=True, to='superlachaise.WikidataCategory'),
        ),
    ]
