# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0006_auto_20170430_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
