# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0007_v0_7_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kind',
        ),
    ]
