# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0007_wikidataentry_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidataentry',
            name='secondary_entries',
            field=models.ManyToManyField(blank=True, related_name='primary_entries', to='superlachaise.WikidataEntry'),
        ),
    ]
