# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0008_v0_8_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediapage',
            name='extract',
            field=models.TextField(blank=True, default=''),
        ),
    ]
