# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0009_wikipediapage_extract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonscategory',
            name='main_image',
        ),
        migrations.AddField(
            model_name='commonscategory',
            name='wikitext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
