# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0009_v0_9_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreV1NodeIDMapping',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('wikidata_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superlachaise.WikidataEntry')),
            ],
            options={
                'verbose_name': 'Store V1 node ID mapping',
                'verbose_name_plural': 'Store V1 node ID mappings',
                'ordering': ['id'],
            },
        ),
    ]
