# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0009_auto_20170502_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidataentry',
            name='secondary_entries',
        ),
        migrations.AddField(
            model_name='wikidataentry',
            name='secondary_wikidata_entries',
            field=models.ManyToManyField(blank=True, related_name='primary_wikidata_entries', to='superlachaise.WikidataEntry'),
        ),
    ]
