# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0009_auto_20170430_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidatacategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wikidata_categories', to='superlachaise.Category'),
        ),
    ]
