# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0010_storev1nodeidmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storev1nodeidmapping',
            options={'ordering': ['id'], 'verbose_name': 'Store V1 node ID mapping', 'verbose_name_plural': 'Store V1 node ID mappings'},
        ),
        migrations.RenameField(
            model_name='storev1nodeidmapping',
            old_name='node_id',
            new_name='id',
        ),
    ]
