# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0011_auto_20170520_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonsfile',
            options={'ordering': ['id'], 'verbose_name': 'Commons file', 'verbose_name_plural': 'Commons files'},
        ),
    ]
