# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0012_auto_20170520_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsfile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commonsfile',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
