# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0013_auto_20170520_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonsfile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonsfile',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
