# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0014_auto_20170520_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstreetmapelement',
            name='element_type',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='openstreetmapelement',
            name='numeric_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
