# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0015_auto_20170521_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openstreetmapelement',
            name='numeric_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
