# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superlachaise', '0016_auto_20170521_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediapage',
            name='language',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='wikipediapage',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
